################### DataSource Configuration ##########################
driverClassName=oracle.jdbc.OracleDriver
url=jdbc:oracle:thin:@localhost:1521/xe
username=example_user
password=example_password
################### DataSource Configuration ##########################
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=example_user
#spring.datasource.password=example_password